name: money2
version: 4.0.1
homepage: https://money2.onepub.dev
documentation: https://money2.onepub.dev
description: Money and Currency classes with fixed precision maths, parsing and formatting. (Money.parse('$2010.00') * 10).format('S CC#,##0') -> $ US20,100
repository: https://github.com/onepub-dev/money.dart
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  decimal: ^2.3.0
  fixed: ^4.0.0
  intl: ^0.19.0
  meta: ^1.9.0
dev_dependencies: 
  lint_hard: ^4.0.0
  test: ^1.17.10
