name: money2
version: 6.0.9
homepage: https://money2.onepub.dev
documentation: https://money2.onepub.dev
description: >
  Money and currency handling for Dart.
  Fixed-decimal math, multi-currency support and conversions, parsing and formatting.
  (Money.parse('$2010.00') * 10).format('SCC#,##0') -> $US20,100

repository: https://github.com/onepub-dev/money.dart
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  characters: ^1.4.0
  decimal: ^3.0.0
  fixed: ^6.0.0
  meta: ^1.9.0
dev_dependencies:
  lint_hard: ^6.2.1
  test: ^1.17.10
  yaml: ^3.1.3

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

